import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar/Navbar";
import StoreProvider from "./StoreProvider";


const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <StoreProvider>
    <html lang="en">
      <body className={`${inter.className} max-w-screen-xl mx-auto`}>
          <Navbar />
          {children}

        {/* </Providers> */}
      </body>
    </html>
        </StoreProvider>
  );
}
